[package]
name = "rustify-web-backend"
version = "0.1.0"
edition = "2021"
description = "Web API backend for Rustify YouTube converter"
license = "MIT"

[dependencies]
rustify-core = { path = "../core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

# Web framework
axum = { version = "0.7", features = ["ws", "multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs", "compression-gzip", "trace", "limit", "validate-request", "add-extension", "request-id", "sensitive-headers"] }
hyper = "1.0"

# WebSocket support
axum-extra = { version = "0.9", features = ["typed-header"] }
tokio-tungstenite = "0.20"

# Async and concurrency
futures = "0.3"

# Security dependencies
argon2 = "0.5"
jsonwebtoken = "9.0"
rand = "0.8"
sha2 = "0.10"
secrecy = "0.8"
validator = { version = "0.18", features = ["derive"] }
sanitize-filename = "0.5"
url = "2.4"
regex = "1.10"
headers = "0.4"
base64 = "0.22"
async-trait = "0.1"
once_cell = "1.19"

# Database (optional for storing conversion history)
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls", "macros", "uuid", "chrono"], optional = true }

# File handling
tempfile = "3.8"

[features]
default = []
database = ["sqlx"]
